version: "3"

services:

  scylla-node4:
    container_name: scylla-node4
    image: scylladb/scylla
    restart: always
    command: --seeds=scylla-node1,scylla-node4 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      default:

  scylla-node5:
    container_name: scylla-node5
    image: scylladb/scylla
    restart: always
    command: --seeds=scylla-node1,scylla-node4 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      default:

  scylla-node6:
    container_name: scylla-node6
    image: scylladb/scylla
    restart: always
    command: --seeds=scylla-node1,scylla-node4 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      default:

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/16
         gateway: 172.21.0.1